# Generated by Django 5.0.6 on 2024-06-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_video_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='price',
            new_name='time',
        ),
    ]
