# Generated by Django 5.0.6 on 2024-06-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_price_video_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='video',
        ),
    ]
